[package]
name = "td_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# plotly = { version = "0.8.4", features = ["kaleido"] }
polars = "0.33.2"
